apiVersion: v1
kind: Service
metadata:
  name: unc-frontend-service
spec:
  selector:
    app: frontend # какие поды обслуживает сервис
  ports:
    - port: 80 # порт сервиса внутри кластера
---
apiVersion: apps/v1 # For versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: unc-frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend # по какой метке искать поды для обслуживания
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend # метка пода
    spec:
      containers:
        - name: unc-frontend-container
          image: afler/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_API_HOST
            - name: BACKEND_API_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_API_PORT