apiVersion: apps/v1 # For versions before 1.9.0 use apps/v1beta2
kind: Deployment    
metadata:   
  name: unc-frontend-deployment
spec:         
  selector:  
    matchLabels:
      app: unc-frontend-pod # по какой метке искать поды для обслуживания
  replicas: 2  
  template:
    metadata:
      labels:  
        app: unc-frontend-pod # метка пода
    spec:
      containers:
        - name: unc-frontend-container
          image: afler/frontend:latest
          ports:
            - containerPort: 80
