server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/${DB_NAME:test-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true