server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/test-api
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true